# Generated by Django 4.0.6 on 2022-09-11 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enchereapp', '0005_alter_comments_date_alter_notification_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 10, 4, 25, 134828)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 10, 4, 25, 135828)),
        ),
        migrations.AlterField(
            model_name='offre',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 10, 4, 25, 132829)),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 10, 4, 25, 133828)),
        ),
    ]
